fix: remove not exist method (#1668)
remove `records` delegation.

It does not exist, then it cause a error.
```
NoMethodError: undefined method `records' for #<Searchkick::Relation
```